services:
  redis:
    image: redis:7
    container_name: superset_redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: superset_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-superset}
      POSTGRES_USER: ${POSTGRES_USER:-superset}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-superset}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-superset}"]
      interval: 5s
      retries: 10
    volumes:
      - superset_db_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:25.4.2.31
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-default}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host", "localhost", "--user", "${CLICKHOUSE_USER:-default}", "--password", "${CLICKHOUSE_PASSWORD:-default}", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    ports:
      - "8088:8088"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      SUPERSET_DATABASE_URI: ${SUPERSET_DATABASE_URI:-postgresql+psycopg2://superset:superset@postgres:5432/superset}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      SUPERSET_ENV: ${SUPERSET_ENV:-dev}
    volumes:
      - superset_home:/app/superset_home
      - ./superset_entrypoint.sh:/app/superset_entrypoint.sh
      - ./superset_config.py:/app/pythonpath/superset_config.py
    entrypoint: ["/bin/sh", "/app/superset_entrypoint.sh"]
    env_file:
      - .env

volumes:
  superset_home:
  superset_db_data:
  clickhouse_data:
