FROM apache/superset:4.1.2

USER root
RUN apt-get update && \
    apt-get install -y gcc pkg-config && \
    pip install clickhouse-connect && \
    pip install --no-cache-dir "sqlalchemy<2.0" clickhouse-sqlalchemy && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
USER superset 